"""Linear algebra over the cyclic ring Z_n (n = 2^k) — the M1.5 deliverable.

`galois` (used throughout the prime-only `qmsd` package) represents the *field* GF(2^k) and its
``null_space``/``matrix_rank`` assume field division, which breaks over a ring with zero divisors.
This module supplies the canonical replacement: the **Howell normal form**, the unique row-echelon
form for a submodule of Z_n^m over the principal-ideal ring Z_n (Storjohann 1998), together with the
operations the ring-code search needs — exact span membership, module enumeration, and the right
kernel / dual module.

Correctness is the priority (the M2 search and the eventual distance/A_d work depend on it): every
Howell-form result is cross-validated against brute-force module enumeration in the test suite.
Kernel/dual are brute-enumerated within a size guard (n small, d in {4,8}); the Howell-based scalable
kernel is the M3 extension.
"""

from __future__ import annotations

from itertools import product
from math import gcd

import numpy as np


def _xgcd(a: int, b: int) -> tuple[int, int, int]:
    """Extended gcd: returns (g, x, y) with x*a + y*b = g, g >= 0."""
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t


def howell_form(matrix, n: int) -> np.ndarray:
    """Howell normal form over Z_n of the row-module generated by ``matrix`` (rows are generators).

    Returns the canonical Howell-form generators (one row per pivot), with leading entries that
    divide n in strictly increasing pivot columns.  The returned rows generate exactly the same
    submodule of Z_n^m as the input rows.
    """
    A = [[int(x) % n for x in row] for row in np.atleast_2d(np.array(matrix, dtype=object))]
    if not A:
        return np.zeros((0, 0), dtype=int)
    ncols = len(A[0])
    rows = [r[:] for r in A]
    r = 0  # pivot pointer
    c = 0
    while c < ncols and r < len(rows):
        # locate a pivot in column c among rows[r:]
        piv = next((i for i in range(r, len(rows)) if rows[i][c] % n != 0), None)
        if piv is None:
            c += 1
            continue
        rows[r], rows[piv] = rows[piv], rows[r]
        # combine all lower rows into row r so column c is zero below the pivot
        for i in range(r + 1, len(rows)):
            if rows[i][c] % n != 0:
                a, b = rows[r][c] % n, rows[i][c] % n
                g, x, y = _xgcd(a, b)
                new_r = [(x * rows[r][j] + y * rows[i][j]) % n for j in range(ncols)]
                new_i = [((a // g) * rows[i][j] - (b // g) * rows[r][j]) % n for j in range(ncols)]
                rows[r], rows[i] = new_r, new_i
        # normalize the pivot to g = gcd(pivot, n), a divisor of n
        arc = rows[r][c] % n
        g = gcd(arc, n)
        modulus = n // g
        if modulus > 1:
            u = pow((arc // g) % modulus, -1, modulus)
            rows[r] = [(u * rows[r][j]) % n for j in range(ncols)]
        # reduce entries above the pivot modulo g
        for i in range(r):
            q = (rows[i][c] % n) // g
            if q:
                rows[i] = [(rows[i][j] - q * rows[r][j]) % n for j in range(ncols)]
        # Howell torsion row t * pivot (t = n // g): zero in column c, enforces the Howell property
        t = n // g
        if t != 1:
            torsion = [(t * rows[r][j]) % n for j in range(ncols)]
            if any(v % n for v in torsion):
                rows.append(torsion)
        r += 1
        c += 1
    H = [row for row in rows if any(v % n for v in row)]
    return np.array(H, dtype=int) if H else np.zeros((0, ncols), dtype=int)


def in_span(v, generators, n: int) -> bool:
    """True iff v is a Z_n-linear combination of the rows of ``generators`` (uses Howell reduction)."""
    H = howell_form(generators, n)
    w = [int(x) % n for x in v]
    ncols = len(w)
    for row in H:
        # pivot column = first nonzero of the Howell row
        cols = np.nonzero(row % n)[0]
        if len(cols) == 0:
            continue
        pc = int(cols[0])
        g = int(row[pc]) % n
        if w[pc] % g != 0:        # leading entry cannot clear this coordinate -> not in span
            return False
        q = (w[pc] % n) // g
        w = [(w[j] - q * int(row[j])) % n for j in range(ncols)]
    return all(x % n == 0 for x in w)


def enumerate_module(generators, n: int, max_size: int = 1 << 20) -> list[tuple[int, ...]]:
    """All elements of the submodule generated by ``generators`` (brute Z_n-combinations)."""
    G = [[int(x) % n for x in row] for row in np.atleast_2d(np.array(generators))]
    if not G:
        return [tuple([0])]
    ncols = len(G[0])
    elems = set()
    for coeffs in product(range(n), repeat=len(G)):
        v = [0] * ncols
        for ci, row in zip(coeffs, G):
            if ci:
                for j in range(ncols):
                    v[j] = (v[j] + ci * row[j]) % n
        elems.add(tuple(v))
        if len(elems) > max_size:
            raise ValueError("module too large to enumerate")
    return sorted(elems)


def module_size(generators, n: int) -> int:
    """|submodule| via Howell form: product over pivots of (n / leading_entry)."""
    H = howell_form(generators, n)
    size = 1
    for row in H:
        cols = np.nonzero(np.array(row) % n)[0]
        if len(cols) == 0:
            continue
        g = int(row[int(cols[0])]) % n
        size *= n // g
    return size


def right_kernel(matrix, n: int, max_enum: int = 1 << 22) -> list[tuple[int, ...]]:
    """All x in Z_n^ncols with matrix @ x == 0 (mod n) — vectorized brute, size-guarded.

    Used for the dual module M^perp = {y : a . y == 0 (mod n), all a in rows}.  ncols small (the
    ring-code search uses n <= ~9, ring 4/8), so vectorized enumeration is exact and fast.
    """
    A = (np.atleast_2d(np.array(matrix, dtype=np.int64)) % n).astype(np.int64)
    m, ncols = A.shape
    if n ** ncols > max_enum:
        raise ValueError(f"right_kernel brute bound exceeded ({n}^{ncols}); needs Howell kernel (M3)")
    grid = np.indices((n,) * ncols).reshape(ncols, -1).T          # (n^ncols, ncols)
    prod = (grid @ A.T) % n                                       # (n^ncols, m)
    mask = np.all(prod == 0, axis=1)
    return [tuple(int(v) for v in row) for row in grid[mask]]


def dual_module(generators, n: int) -> list[tuple[int, ...]]:
    """The orthogonal module M^perp = {y : a . y == 0 (mod n) for all a in M} (brute, size-guarded)."""
    return right_kernel(generators, n)


def right_kernel_howell(matrix, n: int) -> list[list[int]]:
    """GENERATORS of the right kernel {x in Z_n^ncols : matrix @ x == 0 (mod n)} — scalable, no d^n.

    Standard augmented-Howell construction: row-reduce W = [A^T | I] over Z_n; a row whose A^T part
    vanishes has its identity part equal to a kernel vector c (since a combination sum c_i (col_i | e_i)
    = (A c | c)).  Howell's torsion rows make the kernel module complete.  This replaces the brute
    d^ncols enumeration in `right_kernel`/`dual_module` for large block length (the M3 substrate).
    """
    A = (np.atleast_2d(np.array(matrix, dtype=np.int64)) % n).astype(np.int64)
    m, ncols = A.shape
    W = np.hstack([A.T % n, np.eye(ncols, dtype=np.int64)])     # ncols x (m + ncols)
    H = howell_form(W, n)
    gens = []
    for row in H:
        if np.all(np.asarray(row[:m]) % n == 0):
            kv = [int(x) % n for x in row[m:]]
            if any(kv):
                gens.append(kv)
    return gens


def dual_generators(generators, n: int) -> list[list[int]]:
    """Generators of M^perp via the scalable Howell kernel (no d^n enumeration)."""
    return right_kernel_howell(generators, n)
